### ISSUE TITLE
Add tests for client

### ISSUE THREAD

**Issue by lightclient** [lightclient/sheth#43]
I managed to merge #40 without realizing it was broken. There should be some tests for the client to avoid this situations.

**Comment by rohanrk** [comment]
What was the issue/error with #40? It looks like all commits pass CI.

**Comment by lightclient** [comment]
@rohanrk so the issue was that in that PR I removed the `Multiproof` type from the `state` module and began using `Imp`. There are three distinct crates in this repo, the EE, composer library, and client binary. I use `Multiproof` in all of them, but only replaced it with `Imp` in the EE and composer. You'll see in #42 how I fixed that issue. The reason I didn't catch it is because the client has no tests, so that is the goal for this issue.
